//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othello_Game.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador_Partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador_Partida()
        {
            this.Torneo_Partida = new HashSet<Torneo_Partida>();
            this.Jugador_Partida1 = new HashSet<Jugador_Partida>();
        }
    
        public int id_jugador_partida { get; set; }
        public int movimientos { get; set; }
        public string color { get; set; }
        public int cantidad_fichas { get; set; }
        public string id_usuario { get; set; }
        public int id_partida { get; set; }
        public Nullable<int> id_jugador_2 { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneo_Partida> Torneo_Partida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugador_Partida> Jugador_Partida1 { get; set; }
        public virtual Jugador_Partida Jugador_Partida2 { get; set; }
        public virtual Partida Partida { get; set; }
    }
}
