//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthelloGame_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo_T_P
    {
        public long id_E_T_P { get; set; }
        public long id_E_T { get; set; }
        public long id_partida { get; set; }
    
        public virtual Equipo_Torneo Equipo_Torneo { get; set; }
        public virtual Partida Partida { get; set; }
    }
}
