//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthelloGame_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo_Jugador
    {
        public long id_E_J { get; set; }
        public int puntos { get; set; }
        public long id_equipo { get; set; }
        public string id_usuario { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Jugador Jugador { get; set; }
    }
}
