//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthelloGame_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        public long id_ficha { get; set; }
        public int fila { get; set; }
        public int columna { get; set; }
        public long id_partida { get; set; }
        public int id_color { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Partida Partida { get; set; }
    }
}
