//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthelloGame_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador_P_C
    {
        public long id_J_P_C { get; set; }
        public long id_J_P { get; set; }
        public int id_color { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Jugador_Partida Jugador_Partida { get; set; }
    }
}
