//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthelloGame_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador_Partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador_Partida()
        {
            this.Jugador_P_C = new HashSet<Jugador_P_C>();
        }
    
        public long id_J_P { get; set; }
        public int mov { get; set; }
        public string id_Usuario { get; set; }
        public long id_Partida { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugador_P_C> Jugador_P_C { get; set; }
        public virtual Partida Partida { get; set; }
    }
}
