//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthelloGame_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ronda
    {
        public long id_ronda { get; set; }
        public int noRonda { get; set; }
        public int puntos1 { get; set; }
        public int puntos2 { get; set; }
        public long id_equipo1 { get; set; }
        public long id_equipo2 { get; set; }
        public long id_torneo { get; set; }
    
        public virtual Torneo Torneo { get; set; }
    }
}
