//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthelloGame_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneo_Partida
    {
        public int id_torneo_partida { get; set; }
        public int no_ronda { get; set; }
        public int id_torneo { get; set; }
        public int id_partida { get; set; }
    
        public virtual Partida Partida { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
